# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cpptesttrace make clean all
      - name: test
        run: |
          cpptestcli -settings pipeline.properties -module . -input cpptestscan.bdf
      - name: report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports/report.sarif





